#---
apiVersion: v1
kind: Service
metadata:
  name: nacos-svc
  labels:
    app: nacos
spec:
  type: NodePort
  ports:
    - port: 8848
      targetPort: 8848
      protocol: TCP
      name: nacos-http
    - port: 9848
      targetPort: 9848
      protocol: TCP
      name: rpc
    - port: 9849
      protocol: TCP
      targetPort: 9849
      name: raft-rpc
  selector:
    app: nacos
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 7848
      name: rpc
      targetPort: 7848
    - port: 9848
      targetPort: 9848
      name: client-rpc
    - port: 9849
      targetPort: 9849
      name: raft-rpc
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm  
data:
  #mysql.host: "rm-uf66g315pm9r6l6d9.mysql.rds.aliyuncs.com"
  #mysql.host: "rm-uf63068lax47421xo.mysql.rds.aliyuncs.com"
  mysql.host: "mysql.default.svc.cluster.local"
  mysql.db.name: "nacos"
  mysql.port: "3306"
  mysql.user: "nacos"
  #mysql.password: "3&&B=94eKsJQ"
  mysql.password: "nacos@123"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 3 #可配置1~3个副本
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nacos
          imagePullPolicy: IfNotPresent
          image: registry.cn-hangzhou.aliyuncs.com/s-ops/nacos-server:2.0.3 
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 7848
              name: rpc
            - containerPort: 9848
              name: grpc-client
            - containerPort: 9849
              name: grpc
          env:
            - name: NACOS_REPLICAS
              value: "3"   #可配置1~3个副本
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: JVM_XMS
              value: '4096m'
            - name: JVM_XMX
              value: '4096m'
            - name: JVM_XMN
              value: '1024m'
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848 nacos-2.nacos-headless.default.svc.cluster.local:8848"
  selector:
    matchLabels:
      app: nacos
