apiVersion: v1
kind: Endpoints
metadata:
  name: kube-scheduler  # 名称必须和 Service 一致
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler
subsets:
- addresses:
    - ip: 192.168.17.101
    - ip: 192.168.17.102
    - ip: 192.168.17.103
  ports:
  - name: https-metrics
    port: 10259   # endpoint 的目标端口