apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gitops
  name: jnlp-slave
  namespace: kube-ops  
spec:
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: ''
  - name: workspace-volume
    emptyDir: {}      
  - name: maven-cache
    persistentVolumeClaim:
      claimName: maven-cache
  - name: maven-setting
    configMap:
        name: maven-settings
  serviceAccount: jenkins
  imagePullSecrets:
    - name: aliyun-secret
  containers:
  - name: jnlp
    image: registry.cn-hangzhou.aliyuncs.com/s-ops/inbound-agent:4.3-4
    imagePullPolicy: IfNotPresent    
  - name: maven
    image: registry.cn-hangzhou.aliyuncs.com/s-ops/maven:3.5.0-alpine
    imagePullPolicy: IfNotPresent    
    command:
    - cat
    tty: true
    volumeMounts:
    - name: maven-cache
      mountPath: /root/.m2
    - name: maven-setting
      mountPath: /usr/share/maven/conf/settings.xml
      subPath: settings.xml     
  - name: docker
    image: registry.cn-hangzhou.aliyuncs.com/s-ops/docker-gettext-git-xmllint:latest
    imagePullPolicy: IfNotPresent    
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
      readOnly: true
    - name: workspace-volume
      mountPath: /home/jenkins/agent
      readOnly: false      
