apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gitops
  name: jnlp-slave
  namespace: kube-ops  
spec:
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: ''
  - name: workspace-volume
    emptyDir: {}
  serviceAccount: jenkins
  imagePullSecrets:
    - name: aliyun-secret
  containers:
  - name: jnlp
    image: jenkins/inbound-agent
    imagePullPolicy: IfNotPresent    
  - name: docker
    image: registry.cn-hangzhou.aliyuncs.com/s-ops/docker-gettext-git-xmllint:latest
    imagePullPolicy: IfNotPresent    
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
      readOnly: true
    - name: workspace-volume
      mountPath: /home/jenkins/agent
      readOnly: false      

